name = "imgflip-user-feed"
main = "worker.js"
compatibility_date = "2024-11-20"

kv_namespaces = [
  { binding = "NINJAMEMES", id = "853987b9b615439b99efa177b7b29162" }
]

[triggers]
crons = ["0 * * * *"]